#!/usr/bin/perl
use strict;
use warnings;

if ( @ARGV != 1 ) { die "Please enter the Jira number as the command argument"; };

my $jira_num = shift;

my $branch = `git branch -r | grep MW-$jira_num | head -1`;
 print "(debug) branch: $branch\n";

my ($short_name) = $branch =~ m!(MW-[^/]*?$)!;
 print "(debug) short_name: $short_name\n";
 print "(debug) branch: $branch\n";

system ("git fetch wombats");
system ("echo git checkout --track -b $short_name $branch");
print "Proceed?\n";
$/ = "\n"; # if I want to keep this, use readline
my $ans = <STDIN>;
exit if ($ans =~ /n|N/);
system ("git checkout --track -b $short_name $branch");
