#!/usr/bin/perl
# Here's the bash one-liner.  It's described at:
# https://staffwiki.cpanel.net/bin/view/LinuxSupport/OneLiners#Both_of_above_two_one_45liners_combined_into_one
# 
# every_n_min=10;
# tail -12000 /var/log/chkservd.log | awk -v n=$every_n_min '{
#     if ($1~/\[20/) 
#      lastdate=$1" "$2" "$3;
#      split($2,curdate,":");
#      dmin=(curdate[2]-lastmin);
#      dhr=(curdate[1]-lasthr);
#      if ($0!~/Restarting|nable|\*\*|imeout|ailure|terrupt/ && $0~/:-]/) 
#         print lastdate".....";
#         for (i=1; i<=NF; i=i+1) 
#             if ($i~/Restarting|nable|\*\*|imeout|ailure|terrupt|100%|9[89]%|second/) 
#             if ($1~/\[20/) print $1,$2,$3,$(i-1),$i,$(i+1);
#             else print lastdate,$(i-1),$i,$(i+1);
#         if($1~/\[20/ && (lastmin!=0 || lasthr!=0) && (dmin>n || (dhr==1 && (dmin>-(60-n))) || dhr>1 )) print $1,$2,$3" check took longer than "n" minutes. (hr:min): "dhr":"dmin;
#     if ($1~/\[20/) {lastmin=curdate[2]; lasthr=curdate[1]} 
# }'

# Here's 3 major steps I need to do:
# open log file
open my $file, 'chkservd.log' or die "couldn't open file $!";

# make a for loop that reads the file
# break file into hash of hashes called "service_status"

foreach my $line (readline $file) {
    if ($line =~ /regular expression/){
    }
}




# for each element in "service_status", parse services found (into subhash)
#   use my templog="bit of the log"
#  extract status of each service as one variable
#  




close $file;




$service_status->{'2012-08-05 12:38:47'}->{'mysql'} = "Mysql failed to connect";
